// GENERATED BY scripts/media.mjs - DO NOT EDIT BY HAND.
//
// One entry per shipped image: a ~20px blurred WebP as a data URI, the picture's
// own dominant colour, and its real dimensions.
//
// WHY THIS IS INLINE RATHER THAN FETCHED. The placeholder's whole job is to be
// on screen during the first frame, before the photograph it stands in for has
// even been requested. A placeholder that is itself a request cannot do that job
// - it arrives in the same round trip as the thing it was covering for.
//
// The cost is real and small: a few hundred bytes each, which gzip eats well,
// and it buys a background layer that never flashes white and an image grid that
// never reflows. Re-run `npm run media` after adding art.
export type MediaMeta = {
  /** A ~20px WebP, base64. Painted blurred and scaled up under the real one. */
  lqip: string;
  /** The picture's own dominant colour - the ground behind it while it loads. */
  dominant: string;
  w: number;
  h: number;
};

export const MEDIA: Record<string, MediaMeta> = {
  "/art/empty-no-loans.webp": { lqip: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwBACdASoUAA8APu1iqU2ppaQ1MAgCoB2JbACdMoRwN6AAVymPU0ILqMAA+eup541859swlx8CkcB8UpH9c71DmU04/1RbzgZdB0bwP+DuetMG/QuuLJ3Iwdq/1wgA", dominant: "#f8f8f8", w: 800, h: 600 },
  "/art/exposure-interchange.webp": { lqip: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JZgCdMoR2WCKbnIP6QIIaAAD+3G/m2KOdvHWtUuIWQhF6xQDQPb7cBTR34hJWDlHU2JBv7LW/jJrqvvFfAthgAAA=", dominant: "#082828", w: 1600, h: 1067 },
  "/art/kyc-face.webp": { lqip: "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAABQBACdASoUAA0APu1kqk4ppaQiMAgBMB2JYgCuPMgDM8WJA0LXgnO3uFY4AP7rJeVuLXsU0ppf6HCiiDv9sHx3XeGvBDTFHJ9efC3vr13+V2aZoIFVZUnpZ42iHZjC0NMKCAAA", dominant: "#e8e8e8", w: 1600, h: 1067 },
  "/art/kyc-id-front.webp": { lqip: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAADwAwCdASoUAAwAPu1oqk6ppiQiMAgBMB2JZQAAW+gB9GU4xLZxwT8AAP7GRjVShdNbg0B7ztZRLV4vZDTMUESo9rkQ9lWwck+atcAA", dominant: "#c8c8b8", w: 1600, h: 980 },
  "/art/ladder-climb.webp": { lqip: "data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAADQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JagCdLwAA8ew8FcqzBqAA/LRNS/YR2gTazYjEubHnvfLa7Uz1pAZ0+Q8zI+lCUfsmBwX84c/8XzysY7ixsIAnIkrbyipZRR1vpwIHQX/5n+AA", dominant: "#f8c818", w: 1600, h: 1067 },
  "/art/loan-empty-state.webp": { lqip: "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAgCdASoUAA8APu1iqU2ppaOiMAgBMB2JZwAAifQAAP7wlWv56o/6MaM1HsazzAAAAA==", dominant: "#f8f8f8", w: 1600, h: 1200 },
  "/art/ratiba-setup.webp": { lqip: "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JZwAAWljo2gAA/vN1MM7tnmgaHG6CRPdN+IAAAAA=", dominant: "#f8f8f8", w: 1200, h: 675 },
  "/art/repay-done.webp": { lqip: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JbACdMoRwABIx+YoueEcAAPWRzXRLJVpJ8SKnXjYoAX/b77n46bzRJC46LO2b0z2zQuHCxGTlNoR2oqVaRcCZjIV6456AAAA=", dominant: "#684848", w: 1280, h: 720 },
  "/art/score-explained.webp": { lqip: "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JQBOmUABJRmIVdEaVVjmgAP6WqNN0ytlPKJRT9ITbsz0y8/AuD3nqqY1yWkccsYyH+N7mGmVz731n4aia4DuRVM/xI8TKk20wcavCOAA=", dominant: "#080808", w: 1600, h: 1067 },
  "/art/statement-howto.webp": { lqip: "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAADQAwCdASoUAAwAPu1kqU2ppaQiMAgBMB2JQBhQA1xGXaI/oKYwDYAA/somX9uXDP0Oe+NIwytNBuN3yOXVuDQDydwEZfKZnS4sUEumAUDjqR0ZkQLLjgAA", dominant: "#f8f8f8", w: 780, h: 470 },
  "/art/tip-charges.webp": { lqip: "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAwBACdASoUABsAPtleok2oJaMiN/qoAQAbCWMAwoAQZ+aU0eUDEVq9agAA/R+Dy3MZqvl0sc5Gn1nvbtVonH+Lhr2VUGaM+VcNQ1ho0oxZ0D51py9Ds4pxbbjQjO8oAAA=", dominant: "#587858", w: 459, h: 612 },
  "/art/tip-credit-score.webp": { lqip: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAACwAwCdASoUAA4APu1kqU2ppaQiMAgBMB2JZgCdAA3QsGUGy28MAAD+wXozg8HHfrxM4v8NT85yV4mX+GVbLidlURuqUegyO8lXbfapWEvqgvEeoRDzZcWI61CeKh4KSJIdwNWcNAAAAA==", dominant: "#080808", w: 1000, h: 675 },
  "/art/tip-what-moves-limit.webp": { lqip: "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQBACdASoUABQAPu1cqU4ppKOiMBgMATAdiUAVHoFKUYFAbEUyJsKMqdPh6gAA792QOd/K715wauqPQSbAuH3bYuVpCHFA9DGOkbYaE9+gzaL3by2QVfOPABE1w86rmMYV9G2JQGpV+yXMxy4xQv8XlqbD1Bn7F/XuDmXvXmy5WeUmiAheSAAA", dominant: "#080808", w: 447, h: 447 },
  "/images/login/ke-boda.webp": { lqip: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADQAwCdASoUAA0APu1krU6ppaSiMAgBMB2JQBYdgkKqTifNHzg2mQAA/fzgUu0vyW7ktM1SZkk0kxdpicH9BMqHWIXWDnIHC+RrEzmJJ7p8YyPAIbBjSo0D5XEUOAAA", dominant: "#f8f8f8", w: 1400, h: 933 },
  "/images/login/ke-butcher.webp": { lqip: "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JYwCo9BboCSfED3AAAP5T7ETFIYRVxi7Fyk3sSBY7gbb91zIjcYuTVlHK3m2hs+m/klpdXuKoqAAA", dominant: "#182828", w: 1600, h: 1060 },
  "/images/login/ke-duka.webp": { lqip: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JQBOgBDv/8RrC2xWMMAD+6/QvJoWs/ss39AfoOGrNseJ8BopdoKHG40sNbcFsFZcwAA==", dominant: "#181808", w: 1400, h: 933 },
  "/images/login/ke-farmer.webp": { lqip: "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAwCdASoUAAsAPu1krU6ppaSiMAgBMB2JZQAASiHHTGXaDt4AAP7c00JaTdmxelS4u96FZBKLL6OHXeXsXBVgRAoneWbol6eYGKAA", dominant: "#080808", w: 1600, h: 900 },
  "/images/login/ke-fundi.webp": { lqip: "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAAAwBACdASoUAA0APu1iqU2ppaOiMAgBMB2JQBOmUI4ABLGIBsfYNVjTUwAA/sUUXFmJWGvTGJk7VAKTwS+lYmXAtgIq4xqYkgvTo8Bo52s3cY5AAAA=", dominant: "#281808", w: 1400, h: 933 },
  "/images/login/ke-mama-mboga.webp": { lqip: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JYwCsACHwo2oZAjpzBKXY4AD+7iWSR0/8KcTrpugHfalDNYVh17y8NBN6MDD/A+PMOoo32gtBA3/R23iTtRcAAAA=", dominant: "#f8f8f8", w: 1400, h: 932 },
  "/images/login/ke-salon.webp": { lqip: "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwBACdASoUAA0APu1iqU2ppaOiMAgBMB2JagCdMoR3ACXb5NzZRbPiTcAA3zeSk9nySiKFh2sFzYKIkKat7PllWjgDgPjsXeeTNq35h6hOeJSsylggRPamgAA=", dominant: "#483828", w: 1600, h: 1067 },
  "/images/login/ke-tailor.webp": { lqip: "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAADwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JQBWABH+2QOj6+E2qLZ1YAP7fTchnHcZpexenG/F8S6v064PSnROIOzxEh++8aWWYh49BfWDzS/Kjc4/8OE8lLMXJHwtdtBmpKZ1/5qwAAA==", dominant: "#d8d8c8", w: 1600, h: 1200 },
  "/wallpapers/boda-motion.webp": { lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAACwAwCdASoUAAwAPu1orU6ppiSiMAgBMB2JZQDE2CHW7ZhLODEAAAD9U7apVCcoFt4qA6HkeCrCJpsYut2di61kZ4i3FQCd7aoU6vYVwAA=", dominant: "#080808", w: 2560, h: 1600 },
  "/wallpapers/coast.webp": { lqip: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAwAwCdASoUAAwALrV2u12jqampiYC0SyAE6ZQAHUQbj10AAP6UiWJZVs9s5Ik4Q85PWFwdqQ4XW/+2aQGXJ7rWTlxQkNqy6XcBfN5iTggAAA==", dominant: "#c8b8a8", w: 2560, h: 1600 },
  "/wallpapers/linen-dark.webp": { lqip: "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAABwAwCdASoUABcAPu1wr1KtJiQjqAgBoB2JaQAAPPSr3b4OVAAA/vBByOi6ldjbKZTMY5mSLzFa+AAA", dominant: "#080808", w: 1408, h: 1600 },
  "/wallpapers/market-warm.webp": { lqip: "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABwBgCdASoUABwAPu1orFEppaQiqAqpMB2JbACdMtU0T9K8wAYL3X8lI2xX5yfoD648ugOIlgMzd0cIFAAA+KWYhQ3HZDTXuFeGbGi9Fcyn/+BOZSGPE5Pr+J2apmFL7NAQRxKijgJnTm7U0joQpCaWUwBWsGP8yAGG5Hp698vZcAUoURUnx1+2Ysj5eGRq+TIsBNVj7lthwX8EAAA=", dominant: "#f89808", w: 1152, h: 1600 },
  "/wallpapers/mesh-lime.webp": { lqip: "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAAAQBACdASoUAAwAPu1iqU2ppaQiMAgBMB2JQBdl4AAvdAKxv5sbW6dz6AD+7qFRmP6lyPCIuA9EUnvgmRdeNROvNykCizA8ZDKWkiz6X2AAAA==", dominant: "#182828", w: 2560, h: 1600 },
  "/wallpapers/mesh-navy.webp": { lqip: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAwCdASoUAAwAPu1kqk4ppaQiMAgBMB2JYwAAUXy7aTV/ztZ+4AAA/vDfraO+snDx48fcwpiGRH0HxbhiWEklOxG2N+YAAAA=", dominant: "#081828", w: 2560, h: 1600 },
  "/wallpapers/mount-kenya.webp": { lqip: "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQBACdASoUAA8APu1iqk2ppaQiMAgBMB2JYwCdIIjDAWvVjcngxiZYAADyc8vFu6aECKXmOEqlc6Yj8/e2Lgv5Hou5MTmRXdUSJno0aVTOjtwbJ0LCUH9kXXXnwAAA", dominant: "#080808", w: 2176, h: 1600 },
  "/wallpapers/nairobi-dawn.webp": { lqip: "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAACwAwCdASoUAA8APu1kqU2ppaQiMAgBMB2JZQCo9CHHNrwMHA8GAAD92CCrw4OK69ixwyxRNr0oAN4Rg4Ny1dQJksyRYjMo7JeAAA==", dominant: "#989898", w: 2176, h: 1600 },
  "/wallpapers/paper.webp": { lqip: "data:image/webp;base64,UklGRjIAAABXRUJQVlA4ICYAAACwAgCdASoUAAwAPu1iqU2ppaOiMAgBMB2JaQAAeyAA/vB6K2cgAA==", dominant: "#f8f8f8", w: 2560, h: 1600 },
  "/wallpapers/savannah.webp": { lqip: "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAABQAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JagCdMoAEZxAMIgD+6YA/ePMug76ktUlAt/tT5NOD6a9bu+h9Xg8s70fKph1AAAA=", dominant: "#b83828", w: 2560, h: 1600 },
  "/wallpapers/sunset-silhouette.webp": { lqip: "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAwCdASoUAAwAPu1iqU2ppaQiMAgBMB2JaACdACHe0FVvu270/xq4AP7o1qJdNfZmOw3B3l9i222uMXcT8Xds2w4J+GJHJt8diKm0AAA=", dominant: "#080808", w: 2560, h: 1600 },
  "/wallpapers/tea-fields.webp": { lqip: "data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAwBQCdASoUABwAPu1krE+ppSQiMBgIATAdiUAUu3gQHIsNlahq5jo+9jXkR9vzN6UZAAD9JdqhQc1LcbjGU9bsuUcTWCE0ButWAIXmlOcZjwdYewDMzMtSutcaR+Nfsb1Nns6vroDjqphrFgVnx5aRCQOm28C7imQmETcAAAA=", dominant: "#081808", w: 1152, h: 1600 },
};

/** Never throws on an unknown path: a missing entry means "no placeholder", and
 *  every consumer already has to survive that (the file may simply not be drawn
 *  yet). A crash here would take out a screen for the sake of a blur. */
export const metaFor = (src: string | null | undefined): MediaMeta | null =>
  (src ? MEDIA[src] ?? null : null);
